
source ‘https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'JWGeTuiPushCenter_Example' do
  pod 'JWGeTuiPushCenter', :path => '../'

  target 'JWGeTuiPushCenter_Tests' do
    inherit! :search_paths

    
  end
end
